`timescale 1ns/1ps

// Asynchronous assertion and two-clock synchronous release for one clock domain.
module mes50hp_reset_sync (
    input  wire clk,
    input  wire reset_n,
    output wire rst_n
);
    // Keep the two-flop async-assert/sync-release boundary intact so that
    // PDS can target the synchronizer RS pins precisely during timing closure.
    reg [1:0] reset_release /* synthesis syn_preserve = 1 */;

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n)
            reset_release <= 2'b00;
        else
            reset_release <= {reset_release[0], 1'b1};
    end

    assign rst_n = reset_release[1];
endmodule

// Video-domain reset variant.  The reset request is generated by cfg_clk and
// is sampled as ordinary data in the video clock domain, so no asynchronous
// reset pin is exposed to the video synchronizer flops.  The two-cycle local
// release behavior is retained while avoiding a PDS recovery check on RS.
module mes50hp_reset_sync_sync_only (
    input  wire clk,
    input  wire reset_n,
    output wire rst_n
);
    reg [1:0] reset_release /* synthesis syn_preserve = 1 */;

    always @(posedge clk) begin
        if (!reset_n)
            reset_release <= 2'b00;
        else
            reset_release <= {reset_release[0], 1'b1};
    end

    assign rst_n = reset_release[1];
endmodule
