#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Feb  8 18:52:29 2023

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_rx_tx
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_rx_tx
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_constraint "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_loop.fdc"
remove_constraint  -logic -fdc "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_rx_tx.fdc"
add_design "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_loop.v"
remove_design -verilog "C:/Users/w/Desktop/MES50HP/2_demo/07_hdmi_loop/src/hdmi_rx_tx.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -fsm_compiler {original} -top_module hdmi_loop
synthesize -dir {C:/pango/PDS_2021.4-SP2/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
