#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Thu Oct  1 11:33:41 2026

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pixel_fetch_engine
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pixel_fetch_engine
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/brightness_gain.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_gen.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core_optimized.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/gamma_lut.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/gaussian_3x3.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/line_buffer_3x3.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/detect/morphology.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_fetch_engine.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_fetch_if.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/rgb2gray.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/detect/sobel_3x3.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/detect/threshold.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/window_3x3.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/interpolation/bilinear_interp.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_split.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/preprocess/line_ram_1r1w.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/normalize.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_gen.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_split.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/normalize.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core_optimized.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/interpolation/bilinear_interp.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_fetch_engine.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_tile_cache.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/tile_cache_bank_ram.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/memory/pgl50h_tile_cache_bank_ip.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/ddr_burst_reader.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/cached_pixel_fetch_engine.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/control/algorithm_reset_tree.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_image_pipeline.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/clock_reset.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/mes50hp_top.sv"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module mes50hp_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/board_video_control.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/realtime_frame_scheduler.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr_two_client_arbiter.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_rgbx_cache_adapter.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/algorithm_frame_writer.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_frame_reader.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/video_mode_720p30.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/pgl50h_board_top.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/iic_dri.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms72xx_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7200_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7210_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_ctrl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_buf.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_cmd_trans.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_ctrl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_rd_ctrl_top.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_fram_buf/rd_fram_buf.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_fram_buf/wr_fram_buf.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/DDR3_50H/DDR3_50H.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/mes50hp_video_pll/pll.idf"
remove_constraint  -logic -fdc "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/boards/pgl50h/pds/pgl50h_rtl_synth/source/clk.fdc"
add_constraint "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/boards/pgl50h/constraints/pgl50h_board_top.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing

remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/pgl50h_board_top.sv"
remove_constraint  -logic -fdc "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/boards/pgl50h/constraints/pgl50h_board_top.fdc"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/algorithm_frame_writer.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/board_video_control.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/realtime_frame_scheduler.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr_two_client_arbiter.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_frame_reader.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_rgbx_cache_adapter.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/mes50hp_top.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms72xx_ctl.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/video_mode_720p30.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_buf.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_rd_ctrl_top.v"
remove_design C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/mes50hp_video_pll/pll.idf
remove_design C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/DDR3_50H/DDR3_50H.idf
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_image_pipeline.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/control/algorithm_reset_tree.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/iic_dri.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/clock_reset.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7200_ctl.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7210_ctl.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_ctrl.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_cmd_trans.v"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_ctrl.v"
remove_design C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_fram_buf/wr_fram_buf.idf
remove_design C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_fram_buf/rd_fram_buf.idf
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_gen.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core_optimized.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_fetch_engine.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/cached_pixel_fetch_engine.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/interpolation/bilinear_interp.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_split.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/ddr_burst_reader.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/normalize.sv"
remove_design -verilog "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_tile_cache.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/algorithm_frame_writer.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/algorithm_frame_writer_rgbx.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/board_video_control.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/realtime_frame_scheduler.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr_two_client_arbiter.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/clock_reset.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_frame_reader.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_frame_reader_rgbx.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/ddr3_rgbx_cache_adapter.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/mes50hp_top.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/pgl50h_board_top.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/board/pgl50h/video_mode_720p30.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_gen.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/coordinate_split.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_core_optimized.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/control/algorithm_reset_tree.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/distortion_image_pipeline.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/distortion/normalize.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/algorithm/interpolation/bilinear_interp.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/cached_pixel_fetch_engine.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/coordinate_fifo.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/ddr_burst_reader.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_fetch_engine.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/pixel_tile_cache.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/platform/common/memory/tile_cache_bank_ram.sv"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/memory/pgl50h_tile_cache_bank_ip.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/iic_dri.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms72xx_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7200_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/hdmi/ms7210_ctl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_ctrl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_buf.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_cmd_trans.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_ctrl.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_rd_ctrl_top.v"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/wr_fram_buf/wr_fram_buf.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/rtl/vendor/pgl50h/ddr/rd_fram_buf/rd_fram_buf.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/mes50hp_video_pll/pll.idf"
add_design "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/ip/pango/DDR3_50H/DDR3_50H.idf"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module algorithm_frame_writer_rgbx
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
add_constraint "C:/Study/IC_Study/Project/FPGA/Contest/Pango_Micro_FPGA/Distortion-correction/boards/pgl50h/constraints/pgl50h_board_top.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
report_timing 
pnr -gplace_seed 1 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -gplace_seed 1 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -gplace_seed 1 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
