#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sun Oct  4 00:21:21 2026

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module pgl50h_fast_pr_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_fast_pr_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_fast_pr_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_fast_pr_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module pgl50h_fast_pr_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
