#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Mar 29 15:53:12 2023

add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/hdmi_ddr_ov5640_top.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/cmos_8_16bit.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/fram_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/i2c_com.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/iic_dri.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms72xx_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms7200_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms7210_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/power_on_delay.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_ctrl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/reg_config.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/sync_vg.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_cmd_trans.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_ctrl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_rd_ctrl_top.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/pll/pll.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_fram_buf/wr_fram_buf.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_fram_buf/rd_fram_buf.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/DDR3_50H/DDR3_50H.idf"
add_constraint "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/hdmi_ddr_ov5640_top.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream -master_configuration_clock_frequency {40M} 
